import { StyleSheet } from 'react-native';
import {
  sharedHeader,
  sharedHeaderTitle,
  sharedHeaderSubtitle,
  sharedCard,
  sharedCardHeader,
  sharedCardTitle,
  sharedStatusBadge,
  sharedStatusText,
  sharedCardBody,
  sharedCardDescription,
  sharedCardInfo,
  sharedCardLabel,
  sharedCardValue,
  sharedCardActions,
  sharedSecondaryButton,
  sharedSecondaryButtonText,
  sharedPrimaryButton,
  sharedPrimaryButtonText,
  sharedRetryButton,
  sharedRetryButtonText,
  sharedEmptyIcon,
  sharedEmptySubtext,
} from './sharedStyles';

export const clienteHomeStyles = StyleSheet.create({
  header: sharedHeader,
  headerTitle: sharedHeaderTitle,
  headerSubtitle: sharedHeaderSubtitle,
  card: sharedCard,
  cardHeader: sharedCardHeader,
  cardTitle: sharedCardTitle,
  statusBadge: sharedStatusBadge,
  statusText: sharedStatusText,
  cardBody: sharedCardBody,
  cardDescription: sharedCardDescription,
  cardInfo: sharedCardInfo,
  cardLabel: sharedCardLabel,
  cardValue: sharedCardValue,
  cardActions: sharedCardActions,
  detailButton: sharedSecondaryButton,
  detailButtonText: sharedSecondaryButtonText,
  trackButton: sharedPrimaryButton,
  trackButtonText: sharedPrimaryButtonText,
  retryButton: sharedRetryButton,
  retryButtonText: sharedRetryButtonText,
  emptyIcon: sharedEmptyIcon,
  emptySubtext: sharedEmptySubtext,
});

