import { StyleSheet } from 'react-native';

export const clienteSolicitarPedidoStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f5f5f5',
  },
  scrollContent: {
    padding: 20,
    paddingBottom: 40,
  },
  formContainer: {
    backgroundColor: '#fff',
    borderRadius: 15,
    padding: 0,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
    overflow: 'hidden',
  },
  headerSection: {
    backgroundColor: '#110975',
    padding: 25,
    paddingBottom: 20,
    borderTopLeftRadius: 15,
    borderTopRightRadius: 15,
  },
  paymentContainer: {
    backgroundColor: '#fff',
    borderRadius: 15,
    padding: 0,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
    overflow: 'hidden',
  },
  stepTitle: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#fff',
    marginBottom: 8,
    textAlign: 'center',
  },
  stepSubtitle: {
    fontSize: 14,
    color: '#E8E8FF',
    textAlign: 'center',
  },
  section: {
    padding: 20,
    borderBottomWidth: 1,
    borderBottomColor: '#f0f0f0',
  },
  lastSection: {
    borderBottomWidth: 0,
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 20,
  },
  sectionIcon: {
    fontSize: 24,
    marginRight: 10,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#333',
  },
  labelContainer: {
    marginBottom: 8,
  },
  helperText: {
    fontSize: 12,
    color: '#999',
    marginTop: 2,
    fontStyle: 'italic',
  },
  textArea: {
    minHeight: 100,
    textAlignVertical: 'top',
    paddingTop: 12,
  },
  currencyInputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: '#ddd',
    borderRadius: 8,
    paddingLeft: 15,
  },
  currencySymbol: {
    fontSize: 18,
    fontWeight: '600',
    color: '#110975',
    marginRight: 8,
  },
  currencyInput: {
    flex: 1,
    borderWidth: 0,
    paddingLeft: 0,
    fontSize: 18,
    fontWeight: '600',
  },
  freightValueContainer: {
    backgroundColor: '#f9f9f9',
    borderRadius: 10,
    padding: 15,
    borderWidth: 1,
    borderColor: '#e0e0e0',
    minHeight: 120,
    justifyContent: 'center',
  },
  calculatingContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
  },
  calculatingText: {
    fontSize: 14,
    color: '#666',
  },
  valueDisplay: {
    alignItems: 'center',
  },
  valueLabel: {
    fontSize: 12,
    color: '#666',
    marginBottom: 5,
  },
  valueAmount: {
    fontSize: 32,
    fontWeight: 'bold',
    color: '#110975',
    marginBottom: 8,
  },
  distanceText: {
    fontSize: 14,
    color: '#666',
    marginBottom: 10,
  },
  valueBreakdown: {
    width: '100%',
    marginTop: 10,
    paddingTop: 10,
    borderTopWidth: 1,
    borderTopColor: '#e0e0e0',
  },
  breakdownText: {
    fontSize: 12,
    color: '#999',
    textAlign: 'center',
    marginBottom: 3,
  },
  waitingContainer: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  waitingText: {
    fontSize: 14,
    color: '#999',
    textAlign: 'center',
    fontStyle: 'italic',
  },
  addressInput: {
    minHeight: 70,
    textAlignVertical: 'top',
    paddingTop: 12,
  },
  buttonsContainer: {
    flexDirection: 'row',
    gap: 10,
    padding: 20,
    backgroundColor: '#f9f9f9',
  },
  button: {
    flex: 1,
    padding: 16,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  cancelButton: {
    backgroundColor: '#f0f0f0',
    borderWidth: 1,
    borderColor: '#ddd',
  },
  cancelButtonText: {
    color: '#666',
    fontSize: 16,
    fontWeight: '600',
  },
  continueButton: {
    backgroundColor: '#110975',
    shadowColor: '#110975',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 3,
  },
  continueButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: 'bold',
  },
  paymentSummary: {
    backgroundColor: '#f0f0f0',
    borderRadius: 10,
    padding: 15,
    margin: 20,
    marginBottom: 25,
  },
  summaryLabel: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#333',
    marginBottom: 10,
  },
  summaryRow: {
    flexDirection: 'row',
    marginBottom: 8,
  },
  summaryText: {
    fontSize: 14,
    color: '#666',
    width: 80,
  },
  summaryValue: {
    fontSize: 14,
    color: '#333',
    flex: 1,
    fontWeight: '600',
  },
  summaryValueBold: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#110975',
  },
  paymentMethods: {
    marginBottom: 20,
  },
  paymentMethod: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#f5f5f5',
    borderRadius: 10,
    padding: 15,
    marginBottom: 15,
    borderWidth: 2,
    borderColor: 'transparent',
  },
  paymentMethodSelected: {
    borderColor: '#110975',
    backgroundColor: '#E8E8FF',
  },
  paymentIcon: {
    fontSize: 30,
    marginRight: 15,
  },
  paymentLabel: {
    fontSize: 16,
    fontWeight: '600',
    color: '#333',
    flex: 1,
  },
  checkmark: {
    fontSize: 20,
    color: '#110975',
    fontWeight: 'bold',
  },
  buttonDisabled: {
    opacity: 0.5,
  },
  cepRow: {
    flexDirection: 'row',
    gap: 10,
    marginBottom: 15,
  },
  cepField: {
    flex: 2,
  },
  numeroField: {
    flex: 1,
  },
  cepInputContainer: {
    position: 'relative',
    flexDirection: 'row',
    alignItems: 'center',
  },
  cepInput: {
    flex: 1,
  },
  numeroInput: {
    width: '100%',
  },
  cepLoader: {
    position: 'absolute',
    right: 12,
  },
  qrCodeContainer: {
    alignItems: 'center',
    padding: 20,
    paddingTop: 0,
  },
  qrCodeTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#333',
    marginBottom: 20,
    textAlign: 'center',
  },
  qrCodeWrapper: {
    backgroundColor: '#fff',
    padding: 20,
    borderRadius: 15,
    marginBottom: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  devWarning: {
    backgroundColor: '#fff3cd',
    borderWidth: 1,
    borderColor: '#ffc107',
    borderRadius: 8,
    padding: 12,
    marginBottom: 15,
  },
  devWarningText: {
    fontSize: 12,
    color: '#856404',
    textAlign: 'center',
  },
  infoBox: {
    backgroundColor: '#e7f3ff',
    borderColor: '#2196F3',
    borderWidth: 1,
    borderRadius: 8,
    padding: 12,
    marginBottom: 15,
    marginTop: 10,
  },
  infoText: {
    fontSize: 12,
    color: '#0d47a1',
    lineHeight: 18,
  },
  pixCodeContainer: {
    width: '100%',
    marginTop: 20,
    marginBottom: 20,
  },
  pixCodeLabel: {
    fontSize: 14,
    fontWeight: '600',
    color: '#333',
    marginBottom: 10,
  },
  pixCodeBox: {
    backgroundColor: '#f5f5f5',
    borderRadius: 8,
    padding: 12,
    borderWidth: 1,
    borderColor: '#ddd',
    marginBottom: 10,
  },
  pixCodeText: {
    fontSize: 12,
    color: '#333',
    fontFamily: 'monospace',
  },
  copyButton: {
    backgroundColor: '#110975',
    padding: 12,
    borderRadius: 8,
    alignItems: 'center',
  },
  copyButtonText: {
    color: '#fff',
    fontSize: 14,
    fontWeight: '600',
  },
  pixMethodContainer: {
    alignItems: 'center',
    backgroundColor: '#f5f5f5',
    borderRadius: 15,
    padding: 30,
    margin: 20,
    marginBottom: 20,
    borderWidth: 2,
    borderColor: '#110975',
  },
  pixIcon: {
    fontSize: 50,
    marginBottom: 10,
  },
  pixLabel: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#110975',
    marginBottom: 10,
  },
  pixDescription: {
    fontSize: 14,
    color: '#666',
    textAlign: 'center',
  },
  finishButton: {
    backgroundColor: '#110975',
    padding: 16,
    borderRadius: 10,
    alignItems: 'center',
    marginTop: 10,
    shadowColor: '#110975',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 3,
  },
  finishButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: 'bold',
  },
  paymentMethodTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#333',
    marginBottom: 20,
    textAlign: 'center',
  },
  methodSelected: {
    borderColor: '#4caf50',
    borderWidth: 3,
    backgroundColor: '#f1f8f4',
  },
  selectedIndicator: {
    color: '#4caf50',
    fontWeight: 'bold',
    marginTop: 8,
    fontSize: 14,
  },
  cashPaymentContainer: {
    alignItems: 'center',
    padding: 20,
  },
  cashIcon: {
    fontSize: 60,
    marginBottom: 15,
  },
  cashTitle: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#110975',
    marginBottom: 8,
    textAlign: 'center',
  },
  cashSubtitle: {
    fontSize: 16,
    color: '#666',
    marginBottom: 25,
    textAlign: 'center',
  },
  cashValueBox: {
    backgroundColor: '#f0f0f0',
    borderRadius: 15,
    padding: 20,
    marginBottom: 20,
    width: '100%',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: '#110975',
  },
  cashValueLabel: {
    fontSize: 14,
    color: '#666',
    marginBottom: 8,
  },
  cashValueAmount: {
    fontSize: 32,
    fontWeight: 'bold',
    color: '#110975',
  },
  cashInfoBox: {
    backgroundColor: '#e7f3ff',
    borderColor: '#2196F3',
    borderWidth: 1,
    borderRadius: 8,
    padding: 15,
    marginBottom: 20,
    width: '100%',
  },
  cashInfoText: {
    fontSize: 14,
    color: '#0d47a1',
    lineHeight: 20,
    textAlign: 'center',
  },
  pedidoInfoBox: {
    backgroundColor: '#f0f0f0',
    borderRadius: 10,
    padding: 15,
    marginBottom: 20,
    alignItems: 'center',
    borderWidth: 2,
    borderColor: '#110975',
  },
  pedidoInfoLabel: {
    fontSize: 14,
    color: '#666',
    marginBottom: 5,
  },
  pedidoInfoValue: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#110975',
  },
});

