import { StyleSheet } from 'react-native';
import {
  sharedHeader,
  sharedHeaderTitle,
  sharedHeaderSubtitle,
  sharedCard,
  sharedCardHeader,
  sharedCardTitle,
  sharedStatusBadge,
  sharedStatusText,
  sharedCardBody,
  sharedCardDescription,
  sharedCardInfo,
  sharedCardLabel,
  sharedCardValue,
  sharedCardActions,
  sharedPrimaryButton,
  sharedPrimaryButtonText,
  sharedRetryButton,
  sharedRetryButtonText,
  sharedEmptyIcon,
  sharedEmptySubtext,
} from './sharedStyles';

export const entregadorHomeStyles = StyleSheet.create({
  header: sharedHeader,
  headerTitle: sharedHeaderTitle,
  headerSubtitle: sharedHeaderSubtitle,
  card: sharedCard,
  cardHeader: sharedCardHeader,
  cardTitle: sharedCardTitle,
  statusBadge: sharedStatusBadge,
  statusText: sharedStatusText,
  cardBody: sharedCardBody,
  cardDescription: sharedCardDescription,
  cardInfo: sharedCardInfo,
  cardLabel: sharedCardLabel,
  cardValue: sharedCardValue,
  cardActions: {
    ...sharedCardActions,
    alignItems: 'center',
  },
  detailButton: sharedPrimaryButton,
  detailButtonText: sharedPrimaryButtonText,
  locationIndicator: {
    padding: 12,
    backgroundColor: '#E8F5E9',
    borderRadius: 8,
  },
  locationText: {
    color: '#34C759',
    fontSize: 12,
    fontWeight: '600',
  },
  retryButton: sharedRetryButton,
  retryButtonText: sharedRetryButtonText,
  emptyIcon: sharedEmptyIcon,
  emptySubtext: sharedEmptySubtext,
});

